create table payment (
    id int8 generated by default as identity,
    employee_id int8 not null,
    account_id int8 not null,
    amount numeric(19, 2) not null,
    created_date timestamp not null
);

alter table if exists payment
    add constraint FK_account_payment
    foreign key (account_id)
    references account;